/**
 * generated by Xtext 2.25.0
 */
package assignment3.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MathIdeModule extends AbstractMathIdeModule {
}
