/**
 * generated by Xtext 2.25.0
 */
package assignment3.ide;

import assignment3.MathRuntimeModule;
import assignment3.MathStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MathIdeSetup extends MathStandaloneSetup {
  @Override
  public Injector createInjector() {
    MathRuntimeModule _mathRuntimeModule = new MathRuntimeModule();
    MathIdeModule _mathIdeModule = new MathIdeModule();
    return Guice.createInjector(Modules2.mixin(_mathRuntimeModule, _mathIdeModule));
  }
}
