/*
 * generated by Xtext 2.25.0
 */
package assignment3.validation

import assignment3.math.MathExp
import assignment3.math.MathPackage
import assignment3.math.VarBinding
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MathValidator extends AbstractMathValidator {

	public static final String VAR_UNIQUE = 'var_unique'
	
	@Check
	def void uniqueGlobalVariableDefinition(VarBinding binding){
		if((binding.eContainer as MathExp).variables.filter[name == binding.name].size > 1)
			error("Duplicate global variable", MathPackage.eINSTANCE.binding_Name, VAR_UNIQUE)
	}
	
}
