/**
 * generated by Xtext 2.25.0
 */
package assignment3.math;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see assignment3.math.MathPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
