/**
 * generated by Xtext 2.25.0
 */
package assignment3.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Binding</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link assignment3.math.VarBinding#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see assignment3.math.MathPackage#getVarBinding()
 * @model
 * @generated
 */
public interface VarBinding extends Binding
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see assignment3.math.MathPackage#getVarBinding_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link assignment3.math.VarBinding#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

} // VarBinding
