/**
 * generated by Xtext 2.25.0
 */
package assignment3.generator;

import assignment3.math.Binding;
import assignment3.math.Div;
import assignment3.math.Expression;
import assignment3.math.LetBinding;
import assignment3.math.MathExp;
import assignment3.math.MathNumber;
import assignment3.math.Minus;
import assignment3.math.Mult;
import assignment3.math.Plus;
import assignment3.math.VarBinding;
import assignment3.math.VariableUse;
import com.google.common.collect.Iterables;
import java.util.Arrays;
import java.util.Map;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MathGenerator extends AbstractGenerator {
  private static Map<String, Integer> variables;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    Iterable<MathExp> _filter = Iterables.<MathExp>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), MathExp.class);
    for (final MathExp e : _filter) {
      String _string = e.getName().toString();
      String _plus = ("math_expression/" + _string);
      String _plus_1 = (_plus + ".java");
      fsa.generateFile(_plus_1, this.compile(e));
    }
  }
  
  public CharSequence compile(final MathExp math) {
    CharSequence _xblockexpression = null;
    {
      final String class_name = MathExp.class.getName();
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("package math_expression;");
      _builder.newLine();
      _builder.newLine();
      _builder.append("public class ");
      _builder.append(class_name);
      _builder.append(" {");
      _builder.newLineIfNotEmpty();
      {
        EList<VarBinding> _variables = math.getVariables();
        for(final VarBinding exp : _variables) {
          _builder.append("\t");
          _builder.append("public int ");
          String _name = exp.getName();
          _builder.append(_name, "\t");
          _builder.append(";");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("\t");
      _builder.newLine();
      {
        int _size = math.getExternals().size();
        boolean _greaterThan = (_size > 0);
        if (_greaterThan) {
          _builder.append("\t");
          _builder.append("\t");
          _builder.append("private External external");
          _builder.newLine();
          _builder.append("\t");
          _builder.newLine();
          _builder.append("\t");
          _builder.append("\t");
          _builder.append("public ");
          _builder.append(class_name, "\t\t");
          _builder.append("(External external) {");
          _builder.newLineIfNotEmpty();
          _builder.append("\t");
          _builder.append("\t\t");
          _builder.append("this.external = external;");
          _builder.newLine();
          _builder.append("\t");
          _builder.append("\t");
          _builder.append("}");
          _builder.newLine();
        }
      }
      _builder.append("\t");
      _builder.newLine();
      _builder.append("public void compute() {");
      _builder.newLine();
      {
        EList<VarBinding> _variables_1 = math.getVariables();
        for(final VarBinding exp_1 : _variables_1) {
          _builder.append("\t");
          String _name_1 = exp_1.getName();
          _builder.append(_name_1, "\t");
          _builder.append(" = ");
          String _computeExpressionString = MathGenerator.computeExpressionString(exp_1.getExpression());
          _builder.append(_computeExpressionString, "\t");
          _builder.append(";");
          _builder.newLineIfNotEmpty();
        }
      }
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      {
        int _size_1 = math.getExternals().size();
        boolean _greaterThan_1 = (_size_1 > 0);
        if (_greaterThan_1) {
          _builder.append("\t\t");
          _builder.append("public interface External {");
          _builder.newLine();
          _builder.append("\t\t");
          _builder.append("}");
          _builder.newLine();
        }
      }
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _xblockexpression = _builder;
    }
    return _xblockexpression;
  }
  
  protected static String _computeExpressionString(final MathNumber exp) {
    return Integer.valueOf(exp.getValue()).toString();
  }
  
  protected static String _computeExpressionString(final Plus exp) {
    String _computeExpressionString = MathGenerator.computeExpressionString(exp.getLeft());
    String _plus = (_computeExpressionString + " + ");
    String _computeExpressionString_1 = MathGenerator.computeExpressionString(exp.getRight());
    return (_plus + _computeExpressionString_1);
  }
  
  protected static String _computeExpressionString(final Minus exp) {
    String _computeExpressionString = MathGenerator.computeExpressionString(exp.getLeft());
    String _plus = (_computeExpressionString + " - ");
    String _computeExpressionString_1 = MathGenerator.computeExpressionString(exp.getRight());
    return (_plus + _computeExpressionString_1);
  }
  
  protected static String _computeExpressionString(final Mult exp) {
    String _computeExpressionString = MathGenerator.computeExpressionString(exp.getLeft());
    String _plus = (_computeExpressionString + " * ");
    String _computeExpressionString_1 = MathGenerator.computeExpressionString(exp.getRight());
    return (_plus + _computeExpressionString_1);
  }
  
  protected static String _computeExpressionString(final Div exp) {
    String _computeExpressionString = MathGenerator.computeExpressionString(exp.getLeft());
    String _plus = (_computeExpressionString + " / ");
    String _computeExpressionString_1 = MathGenerator.computeExpressionString(exp.getRight());
    return (_plus + _computeExpressionString_1);
  }
  
  protected static int _computeExpression(final VarBinding binding) {
    MathGenerator.variables.put(binding.getName(), Integer.valueOf(MathGenerator.computeExpression(binding.getExpression())));
    return (MathGenerator.variables.get(binding.getName())).intValue();
  }
  
  protected static int _computeExpression(final MathNumber exp) {
    return exp.getValue();
  }
  
  protected static int _computeExpression(final Plus exp) {
    int _computeExpression = MathGenerator.computeExpression(exp.getLeft());
    int _computeExpression_1 = MathGenerator.computeExpression(exp.getRight());
    return (_computeExpression + _computeExpression_1);
  }
  
  protected static int _computeExpression(final Minus exp) {
    int _computeExpression = MathGenerator.computeExpression(exp.getLeft());
    int _computeExpression_1 = MathGenerator.computeExpression(exp.getRight());
    return (_computeExpression - _computeExpression_1);
  }
  
  protected static int _computeExpression(final Mult exp) {
    int _computeExpression = MathGenerator.computeExpression(exp.getLeft());
    int _computeExpression_1 = MathGenerator.computeExpression(exp.getRight());
    return (_computeExpression * _computeExpression_1);
  }
  
  protected static int _computeExpression(final Div exp) {
    int _computeExpression = MathGenerator.computeExpression(exp.getLeft());
    int _computeExpression_1 = MathGenerator.computeExpression(exp.getRight());
    return (_computeExpression / _computeExpression_1);
  }
  
  protected static int _computeExpression(final LetBinding exp) {
    return MathGenerator.computeExpression(exp.getBody());
  }
  
  protected static int _computeExpression(final VariableUse exp) {
    return MathGenerator.computeBinding(exp.getRef());
  }
  
  protected static int _computeBinding(final VarBinding binding) {
    Integer _xblockexpression = null;
    {
      boolean _containsKey = MathGenerator.variables.containsKey(binding.getName());
      boolean _not = (!_containsKey);
      if (_not) {
        MathGenerator.computeExpression(binding);
      }
      _xblockexpression = MathGenerator.variables.get(binding.getName());
    }
    return (_xblockexpression).intValue();
  }
  
  protected static int _computeBinding(final LetBinding binding) {
    return MathGenerator.computeExpression(binding.getBinding());
  }
  
  public static String computeExpressionString(final Expression exp) {
    if (exp instanceof Div) {
      return _computeExpressionString((Div)exp);
    } else if (exp instanceof MathNumber) {
      return _computeExpressionString((MathNumber)exp);
    } else if (exp instanceof Minus) {
      return _computeExpressionString((Minus)exp);
    } else if (exp instanceof Mult) {
      return _computeExpressionString((Mult)exp);
    } else if (exp instanceof Plus) {
      return _computeExpressionString((Plus)exp);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(exp).toString());
    }
  }
  
  public static int computeExpression(final EObject exp) {
    if (exp instanceof Div) {
      return _computeExpression((Div)exp);
    } else if (exp instanceof LetBinding) {
      return _computeExpression((LetBinding)exp);
    } else if (exp instanceof MathNumber) {
      return _computeExpression((MathNumber)exp);
    } else if (exp instanceof Minus) {
      return _computeExpression((Minus)exp);
    } else if (exp instanceof Mult) {
      return _computeExpression((Mult)exp);
    } else if (exp instanceof Plus) {
      return _computeExpression((Plus)exp);
    } else if (exp instanceof VarBinding) {
      return _computeExpression((VarBinding)exp);
    } else if (exp instanceof VariableUse) {
      return _computeExpression((VariableUse)exp);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(exp).toString());
    }
  }
  
  public static int computeBinding(final Binding binding) {
    if (binding instanceof LetBinding) {
      return _computeBinding((LetBinding)binding);
    } else if (binding instanceof VarBinding) {
      return _computeBinding((VarBinding)binding);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(binding).toString());
    }
  }
}
