/*
 * generated by Xtext 2.25.0
 */
package assignment3.ui.tests;

import assignment3.ui.internal.Assignment3Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Assignment3Activator.getInstance().getInjector("assignment3.Math");
	}

}
